name: Tox

on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - run: sudo apt-get install libpq-dev
      - run: pip install tox
      - run: tox -e py36-django111,py36-django20,py36-django21
